// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/atualizar-licenca": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Atualiza o status de uma licença com base no código da licença.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Licenças"
                ],
                "summary": "Atualizar status da licença",
                "parameters": [
                    {
                        "description": "Código da licença e novo status",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "codigo": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Status atualizado com sucesso",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Erro nos dados enviados",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Licença não encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Erro interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/cadastrar-usuario": {
            "post": {
                "description": "Cria um novo usuário no banco de dados.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Autenticação"
                ],
                "summary": "Cadastro de usuário",
                "parameters": [
                    {
                        "description": "Dados do usuário",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UsuarioRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Usuário cadastrado com sucesso",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Erro nos dados enviados",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/criar-licenca": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Gera uma ou mais licenças baseadas na compra e envia um único e-mail com os códigos.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Licenças"
                ],
                "summary": "Criar licença(s)",
                "parameters": [
                    {
                        "description": "Dados da licença",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LicenseRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Licenças criadas com sucesso"
                    },
                    "400": {
                        "description": "Erro nos dados enviados"
                    },
                    "401": {
                        "description": "Não autorizado"
                    },
                    "500": {
                        "description": "Erro interno ao processar a licença"
                    }
                }
            }
        },
        "/licencas": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna todas as licenças cadastradas ou filtra por código da compra e/ou código da licença.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Licenças"
                ],
                "summary": "Lista licenças",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código da compra para filtrar",
                        "name": "codigo_compra",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Código da licença para filtrar",
                        "name": "codigo",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.License"
                            }
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Erro interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Autentica o usuário e retorna um token JWT para acesso às rotas protegidas.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Autenticação"
                ],
                "summary": "Login do usuário",
                "parameters": [
                    {
                        "description": "Credenciais do usuário",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "email": {
                                    "type": "string"
                                },
                                "senha": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Token JWT",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Erro nos dados enviados",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Credenciais inválidas",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Usuário sem permissão",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/webhook/vtex-vendas": {
            "post": {
                "description": "Recebe eventos da VTEX com dados do pedido e inicia o processo de geração de licença automática",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Webhook"
                ],
                "summary": "Webhook da VTEX para pedidos",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Assinatura HMAC do corpo da requisição",
                        "name": "X-VTEX-HMAC-SHA256",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Evento de pedido VTEX",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.VtexOrderEvent"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Erro ao ler body ou JSON inválido",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Assinatura inválida",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.VtexOrderEvent": {
            "type": "object",
            "properties": {
                "currentState": {
                    "type": "string"
                },
                "lastChange": {
                    "type": "string"
                },
                "orderId": {
                    "type": "string"
                },
                "salesChannel": {
                    "type": "string"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "mensagem de erro"
                }
            }
        },
        "models.License": {
            "type": "object",
            "properties": {
                "avisoExpiracaoEnviado": {
                    "type": "boolean"
                },
                "codigo": {
                    "type": "string"
                },
                "codigo_compra": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                },
                "quantidade": {
                    "description": "Novo campo para múltiplas licenças",
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "ultimoAvisoRenovacao": {
                    "type": "boolean"
                },
                "updated_at": {
                    "type": "string"
                },
                "validade": {
                    "type": "integer"
                }
            }
        },
        "models.LicenseRequest": {
            "type": "object",
            "properties": {
                "codigo_compra": {
                    "type": "string",
                    "example": "1234abef"
                },
                "email": {
                    "type": "string",
                    "example": "email do usuário"
                },
                "nome": {
                    "type": "string",
                    "example": "nome do usuário"
                },
                "quantidade": {
                    "description": "Novo campo para múltiplas licenças",
                    "type": "integer"
                },
                "teste": {
                    "description": "opcional",
                    "type": "boolean"
                },
                "validade": {
                    "type": "integer",
                    "example": 36
                }
            }
        },
        "models.UsuarioRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "teste@exemplo.com"
                },
                "senha": {
                    "type": "string",
                    "example": "123456"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Insira o token no formato ` + "`" + `Bearer {seu_token}` + "`" + `",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "api-licenca.intelbras-cve-pro.com.br",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API de Licenças",
	Description:      "API para gerenciar licenças de software.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
